### ISSUE TITLE
200 character maximum

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.js#19] opened 2023-07-19 20:51 UTC
https://github.com/sillsdev/machine.js/blob/8478442b6ac3b33544bd64f674dfe874802f45f2/src/translation/constants.ts#L1

This should be 200 segments, but it got converted to characters.  It should be something like 2000 - and have the name changed to MAX_CHARACTER_LENGTH.

**Comment by Nateowami** [comment] 2023-08-11 15:44
I just ran the numbers on the live database, and found the following:

Character limit | Segments included
----------------|-----------------------------
200             | 93.29%
319             | 99%
374             | 99.5%
476             | 99.8%
591             | 99.9%
1106            | 99.99%

These numbers were calculated by finding projects with statistical translation suggestions enabled, and then looking at the lengths of the segments in their source projects. I have a spreadsheet with all the data that I can share if anyone wants it.

What the numbers show is that increasing the character limit from 200 to the mid 300s would have a major effect. Right now roughly 1 in 15 segments cannot be translated due to length.

The longest segment I found was 12541 characters, which shows the need for having a limit.

I also ran the numbers on the specific project the user the reported the problem was working with, and they were fairly close to the overall numbers.

**Comment by johnml1135** [comment] 2023-08-11 18:34
@ddaspit - do you have any objection to raising this to 400?  That should catch the vast majority of cases...

**Comment by ddaspit** [comment] 2023-08-30 17:56
This has been fixed on the master branch.

**Comment by Nateowami** [comment] 2023-08-30 18:06
@ddaspit Do I understand correctly that the limit was supposed to be words/tokens, not characters?

**Comment by ddaspit** [comment] 2023-08-30 18:09
Yes, that is correct. This was a regression that was introduced with the changes to work with Serval.

**Comment by Nateowami** [comment] 2023-08-30 18:10
@ddaspit We haven't flipped the switch to connected live to Serval yet. Are we safe to update Machine.js while still running the in-process Machine at 2.5.14?

**Comment by ddaspit** [comment] 2023-08-30 18:26
If you have already upgraded to Machine.js 2.4, then it should be safe to update to 2.4.2.

**Comment by Nateowami** [comment] 2023-09-20 04:40
This is still telling users segments are too long when it shouldn't.

In package.json we have:
```
"@sillsdev/machine": "^2.4.2",
```
And yet this verse:
> En los días en que los jueces gobernaban Israel, un hambre severa azotó la tierra. Por eso, un hombre de Belén de Judá dejó su casa y se fue a vivir a la tierra de Moab, junto con su esposa y sus dos hijos.

In one of my test projects, causes the message "This verse is too long to generate suggestions."

**Comment by ddaspit** [comment] 2023-09-20 21:14
@Nateowami [SF is incorrectly checking the length of the string](https://github.com/sillsdev/web-xforge/blob/af8effd5f480247cdff4cec18444047f24d2b05e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1381) instead of checking the number of word tokens. SF should use the `InteractiveTranslator.isSegmentValid` property to determine if the segment is too long.

**Closed by ddaspit** 2023-09-20 21:14 UTC
